### ISSUE TITLE
Installing on patch 7/8 causes this - will there be future support?

### ISSUE THREAD

**Issue by ghost** [gennariarmando/iv-console-select-menu#1]
I get this very specific error when installing the mod on patch 8, with fusionfix 2.0 and console visuals included. As a clarification, will there be support for patch 7/8 in the future?

![crash](https://github.com/gennariarmando/iv-console-select-menu/assets/54059259/bc4a1fba-be01-4d93-809f-a5f107fc9863)

**Comment by gennariarmando** [comment]
No there won't be no support for old versions of the game.
